#ECCConsole

CC = gcc
CXX = g++
AR = ar
LD = $(CXX)


WINDRES = windres
OBJDIR = obj/gnu
INC = -Iinclude -I../../BASE/include
#DEFINC=-D_USE_UTF8_ -DNEOUSEMBCS -DNEO_STATIC -DLSA_EXPORTS_NOUSE -D__NOTUSEOPENSSL__
DEFCFLAGS=-Wall -O2 -fPIC 
DEFINC=-D_USE_UTF8_ -DNEOUSEMBCS -DNEO_STATIC -DLSA_EXPORTS_NOUSE
# -DNEODEBUG
DEFCFLAGS=-Wall -O2 -fPIC -Wl,-Bsymbolic
LIB = ../lib/gnu/libcrypto.a
LDFLAGS      = -shared -fPIC  -L../lib/gnu -lslab_usb_spi -ldl
OUTDIR = ../lib/gnu

